# Generated by Django 3.1 on 2020-08-21 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('host_token', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Host Token')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Session_ID')),
                ('started_time', models.DateTimeField(auto_now=True, verbose_name='Start Time')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='End Time')),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffle_backend.host')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('ip_address', models.GenericIPAddressField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffle_backend.session')),
            ],
            options={
                'unique_together': {('ip_address', 'session')},
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raffle_backend.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffle_backend.participant')),
            ],
            options={
                'unique_together': {('user', 'session')},
            },
        ),
    ]
